/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "background": "#F7F5F0",
        "surface": "#FFFFFF",
        "surface-secondary": "#F0EDE4",
        "surface-muted": "#EFEBE0",
        "border": "#E3DFD3",
        "border-muted": "#D8D3C4",
        "text-primary": "#1B1B1B",
        "text-secondary": "#4A5D57",
        "text-muted": "#8A8A7E",
        "text-inverse": "#FFFFFF",
        "brand-forest": "#1B4332",
        "brand-forest-dark": "#122E22",
        "brand-teal": "#2A9D8F",
        "brand-teal-dark": "#1F776C",
        "brand-teal-light": "#E4F3F1",
        "brand-gold": "#C9922B",
        "brand-gold-light": "#F8EEDB",
        "accent": "#2A9D8F",
        "accent-dark": "#1F776C",
        "accent-light": "#E4F3F1",
        "accent-foreground": "#FFFFFF",
        "risk-safe": "#3C8F5C",
        "risk-safe-light": "#E4F3E9",
        "risk-watch": "#C9922B",
        "risk-watch-light": "#F8EEDB",
        "risk-stress": "#C1442D",
        "risk-stress-light": "#F8E4DF",
        "success": "#3C8F5C",
        "success-light": "#E4F3E9",
        "warning": "#C9922B",
        "warning-light": "#F8EEDB",
        "danger": "#C1442D",
        "danger-light": "#F8E4DF",
        "info": "#3771C8",
        "info-light": "#E5EDF9",
        "offline-badge-bg": "#4A5D57",
        "offline-badge-text": "#FFFFFF",
      },
      fontFamily: {
        sans: ["NotoSans_400Regular"],
        "sans-medium": ["NotoSans_500Medium"],
        "sans-semibold": ["NotoSans_600SemiBold"],
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        pill: "9999px",
      },
    },
  },
  plugins: [],
};
